pcall(require, "luacov")
local utils = require("neo-tree.utils")

describe("utils.job", function()
  it("returns output and closes the process handle", function()
    local job = assert(utils.job({ "sh", "-c", "echo out; echo err >&2; exit 3" }))
    local result = job.wait(5000)
    assert.are.same(3, result.code)
    assert.are.same("out\n", table.concat(result.stdout))
    assert.are.same("err\n", table.concat(result.stderr))
    assert.is_true(job.handle:is_closing())
  end)

  it("returns the error when the command cannot be spawned", function()
    local job, err = utils.job({ "neo-tree-nonexistent-command" })
    assert.is_nil(job)
    assert.is_truthy(err)
  end)
end)
