name: Lua Type Check
on:
  pull_request: ~
  push:
    branches:
      - '*'

jobs:
  llscheck:
    strategy:
      matrix:
        neovim: ["0.8", "0.9", "0.10", "nightly"]
        lua: ["5.1", "luajit-master"]
    runs-on: ubuntu-latest
    name: llscheck

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: luarocks/gh-actions-lua@v10
      with:
        luaVersion: ${{matrix.lua}}

    - uses: luarocks/gh-actions-luarocks@v5

    - name: build
      run: |
        luarocks install llscheck

    - name: Install lua-language-server
      uses: jdx/mise-action@v2
      with:
        mise_toml: |
          [tools]
          neovim = "${{ matrix.neovim }}"
          lua-language-server = "latest"

    - name: Print Version
      run: |
        lua-language-server --version
