name: lua_ls-typecheck

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Type Check Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout dependency neodev
        uses: actions/checkout@v3
        with:
          repository: "folke/neodev.nvim"
          path: "deps/neodev.nvim"

      - name: Checkout dependency plenary
        uses: actions/checkout@v3
        with:
          repository: "nvim-lua/plenary.nvim"
          path: "deps/plenary.nvim"

      - name: Checkout dependency nvim-web-devicons
        uses: actions/checkout@v3
        with:
          repository: "nvim-tree/nvim-web-devicons" # not strictly required, but recommended
          path: "deps/nvim-web-devicons"

      - name: Checkout dependency nui
        uses: actions/checkout@v3
        with:
          repository: "MunifTanjim/nui.nvim"
          path: "deps/nui.nvim"

      - name: Print Filetree
        run: ls -la && ls -la deps

      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0.1.2
        with:
          configpath: .github/workflows/.luarc.json
          directories: |
            lua/neo-tree/defaults.lua
            lua/neo-tree/log.lua
            lua/neo-tree/collections.lua
            lua/neo-tree/setup/deprecations.lua
            lua/neo-tree/setup/init.lua
